var lineColorDictShanghai = {};
lineColorDictShanghai["01"] = '<span style="background-color:#e3002b;color:white">&nbsp;<strong>1</strong>&nbsp;</span>';
lineColorDictShanghai["02"] = '<span style="background-color:#8cc220">&nbsp;<strong>2</strong>&nbsp;</span>';
lineColorDictShanghai["03"] = '<span style="background-color:#fcd600">&nbsp;<strong>3</strong>&nbsp;</span>';
lineColorDictShanghai["04"] = '<span style="background-color:#461d84;color:white">&nbsp;<strong>4</strong>&nbsp;</span>';
lineColorDictShanghai["05"] = '<span style="background-color:#944d9a;color:white">&nbsp;<strong>5</strong>&nbsp;</span>';
lineColorDictShanghai["06"] = '<span style="background-color:#d40068;color:white">&nbsp;<strong>6</strong>&nbsp;</span>';
lineColorDictShanghai["07"] = '<span style="background-color:#ed6f00">&nbsp;<strong>7</strong>&nbsp;</span>';
lineColorDictShanghai["08"] = '<span style="background-color:#0094d8;color:white">&nbsp;<strong>8</strong>&nbsp;</span>';
lineColorDictShanghai["09"] = '<span style="background-color:#87caed">&nbsp;<strong>9</strong>&nbsp;</span>';
lineColorDictShanghai["10"] = '<span style="background-color:#c6afd4"><strong>10</strong></span>';
lineColorDictShanghai["11"] = '<span style="background-color:#871c2b;color:white"><strong>11</strong></span>';
lineColorDictShanghai["12"] = '<span style="background-color:#007a60;color:white"><strong>12</strong></span>';
lineColorDictShanghai["13"] = '<span style="background-color:#e999c0"><strong>13</strong></span>';
lineColorDictShanghai["14"] = '<span style="background-color:#626020;color:white"><strong>14</strong></span>';
lineColorDictShanghai["15"] = '<span style="background-color:#bca886"><strong>15</strong></span>';
lineColorDictShanghai["16"] = '<span style="background-color:#98d1c0"><strong>16</strong></span>';
lineColorDictShanghai["17"] = '<span style="background-color:#bc796f;color:white"><strong>17</strong></span>';
lineColorDictShanghai["18"] = '<span style="background-color:#c4984f"><strong>18</strong></span>';
lineColorDictShanghai["19"] = '<span style="background-color:#f5ab78"><strong>19</strong></span>';
lineColorDictShanghai["20"] = '<span style="background-color:#009f65;color:white"><strong>20</strong></span>';
lineColorDictShanghai["21"] = '<span style="background-color:#f7af00"><strong>21</strong></span>';
lineColorDictShanghai["22"] = '<span style="border: 3.5px solid #5f376f; padding: 0px; border-radius:20%"><strong>22</strong></span>';
lineColorDictShanghai["23"] = '<span style="background-color:#b0d478"><strong>23</strong></span>';
lineColorDictShanghai["0P"] = '<span style="background-color:#b5b5b6;color:white">&nbsp;<strong>浦江线</strong>&nbsp;</span>';
lineColorDictShanghai["51"] = '<span style="background-color:#a9a9a9;color:white">&nbsp;<strong>市域机场线</strong>&nbsp;</span>';

//lineColorDictShanghai["0P"] = '<span style="background-color:#b5b5b6;color:white">&nbsp;<strong>P</strong>&nbsp;</span>';
//lineColorDictShanghai["51"] = '<span style="border: 4px solid #ff99ff; padding: 0px; border-radius:100%">&nbsp;<strong>A</strong>&nbsp;</span>';
